---
title: "Spatial_Modeling_Assignment"
author: "Julie Raiguel"
date: "February 15, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Question 1
```{r}
library(vegan)
data(BCI)
## UTM Coordinates (in metres)
BCI_xy = data.frame(x = rep(seq(625754, 626654, by=100), each=5), y = rep(seq(1011569,  1011969, by=100), len=50))
```

```{r}
head(BCI)
nrow(BCI)

head(BCI_xy)
nrow(BCI_xy)
```

```{r}
plot(BCI_xy)
```

```{r}
BCI_richness = apply(BCI, 1, function(x) sum(x > 0))
hist(BCI_richness)
```

```{r}
col_brks = hist(BCI_richness, plot=F)$breaks
col_indices = as.numeric(cut(BCI_richness, col_brks))
cols = rev(terrain.colors(length(col_brks)))
plot(BCI_xy, cex=2, pch=19, col=cols[col_indices])
```

```{r}
sum_species = sapply(BCI, sum)

boxplot(sum_species)

quantile(sum_species, 0.50)

```


```{r}
rare_sp = BCI

for (i in ncol(BCI):1) {
  sp_abundance = sum(BCI[ , i])
  if(sp_abundance > 25 | sp_abundance == 1) {
    print(colnames(BCI)[i])
    rare_sp = rare_sp[, -i]
  }
}  

ncol(rare_sp)


```

```{r}
common_sp = BCI

for (i in ncol(BCI):1) {
  sp_abundance = sum(BCI[ , i])
  if(sp_abundance <= 25) {
    print(colnames(BCI)[i])
    common_sp = common_sp[, -i]
  }
}  

ncol(common_sp)
```

```{r}
ncol(BCI)
```
```{r}
head(common_sp)
head(rare_sp)
```
```{r}
xy_dist = dist(BCI_xy)
comm_dist = vegdist(common_sp)
rare_dist = vegdist(rare_sp)
```

```{r}
plot(xy_dist, comm_dist)
abline(lm(comm_dist ~ xy_dist), lwd=3, col='red')
lines(lowess(xy_dist, comm_dist), lwd=3, col='green')

```

```{r}
plot(xy_dist, rare_dist)
abline(lm(rare_dist ~ xy_dist), lwd=3, col='red')
lines(lowess(xy_dist, rare_dist), lwd=3, col='green')
```

```{r}
comm_mantel = mantel(xy_dist, comm_dist)
comm_mantel
```

```{r}
rare_mantel = mantel(xy_dist, rare_dist)
rare_mantel
```

```{r}
comm_corlog = mantel.correlog(comm_dist, xy_dist)
rare_corlog = mantel.correlog(rare_dist, xy_dist)

comm_corlog
```

```{r}
rare_corlog
```

```{r}
par(mfrow=c(1,2))
plot(rare_corlog)
mtext(side=3, 'Rare Species')

plot(comm_corlog)
mtext(side=3, 'Community Species')

```
##Question 2

```{r}
predict_sp = BCI

for (i in ncol(BCI):1) {
  sp_abundance = sum(BCI[ , i])
  if(colnames(BCI)[i] != "Cordia.lasiocalyx" & 
     colnames(BCI)[i] != "Hirtella.triandra" &
     colnames(BCI)[i] != "Picramnia.latifolia" &
     colnames(BCI)[i] != "Quassia.amara" & 
     colnames(BCI)[i] != "Tabernaemontana.arborea" &
     colnames(BCI)[i] != "Trattinnickia.aspera" &
     colnames(BCI)[i] != "Xylopia.macrantha" & 
     colnames(BCI)[i] != "Drypetes.standleyi") {
    
    predict_sp = predict_sp[, -i]
  }
}  

colnames(predict_sp)

```



```{r}


```

